enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

# Enable PnP for better dependency management
pnpMode: loose

# Configure package extensions for Next.js
packageExtensions:
  "next@*":
    dependencies:
      "@swc/core": "*"
      "@swc/helpers": "*"
      "swc": "*"

# Set the default registry
npmScopes:
  default:
    npmRegistryServer: "https://registry.npmjs.org"
